name: HaskellNixCabalStarter
version: '0.1.0.0'
author: HaskellNixCabalStarter
maintainer: HaskellNixCabalStarter
license: MIT
dependencies:
- base >=4.12 && <4.13
- webdriver-w3c
executables:
  app:
    source-dirs: src
    main: Main.hs
